version: '2.1'
services:
  server:
    build:
      context: ../
      dockerfile: docker/dev.dockerfile
    ports:
      - 3000:3000
    volumes:
      - ../components:/app/components
      - ../pages:/app/pages
      - ../server:/app/server
      - ../static:/app/static
      - ../styles:/app/styles
