version: '2.1'
services:
  server:
    build:
      context: ../
      dockerfile: docker/dev.dockerfile
    environment:
      - CUMPA_DB=mysql://root:root@db:3306/cumpa
    ports:
      - 3000:3000
    volumes:
      - ../components:/app/components
      - ../pages:/app/pages
      - ../server:/app/server
      - ../static:/app/static
      - ../styles:/app/styles
    # depends_on:
    #   db:
    #     condition: service_healthy
  db:
    container_name: cumpa_db
    image: mysql:8.0.17
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 9995:3306
    volumes:
      - /var/lib/cumpa-mysql/data
